name: Build
on:
  push:
    branches:
      - master
      - actions

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_BACKEND_CONFIG: ${{ secrets.TF_BACKEND_CONFIG }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - run: echo "$TF_BACKEND_CONFIG" > backend.conf
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9
      - run: terraform init -backend-config=backend.conf
      - id: plan
        run: terraform plan -no-color